---
title: "Course Project1"
author: "Devender Singh Saini"
date: "June 26, 2016"
output: html_document
---

# Analysis
## Loading and processing the data


```{r,echo=TRUE}
act <- read.csv("activity.csv",header = T)
act$date <- as.Date(act$date)
str(act)
act1 <- act[complete.cases(act),]

```

## What is mean total number of steps taken per day?


```{r,echo=TRUE}
stepperday <- tapply(act1$steps,act1$date,sum)
library(ggplot2)
qplot(stepperday, xlab = "Steps per day", ylab = "Frequency",binwidth = 500)
mean(stepperday)
median(stepperday)
```



## What is the average daily activity pattern?

```{r,echo=TRUE}
intervalplot <- tapply(act1$steps,act1$interval, mean)
plot(x = names(intervalplot), y =intervalplot, type= "l", xlab = "Interval", ylab = "meanstepperinterval")
max(intervalplot)
intervalplot[intervalplot==max(intervalplot)]


```

## Imputing missing values

```{r,echo=TRUE}
sum(!complete.cases(act))
act_dum <- act
act_dum[which(is.na(act_dum$steps)),1] <-  intervalplot[as.character(act_dum[which(is.na(act_dum$steps)),3])]
sum(is.na(act_dum$steps))

new_stepperday <- tapply(act_dum$steps, act_dum$date, sum)
qplot(new_stepperday, xlab = "Steps per day", ylab = "Frequency",binwidth = 500)
mean(new_stepperday)
median(new_stepperday)

```

## Are there differences in activity patterns between weekdays and weekends?

```{r,echo=TRUE}
library(dplyr)
act_dum <- mutate(act_dum,weekkind = ifelse(weekdays(act_dum$date) =="Saturday"| weekdays(act_dum$date)=="Sunday","Weekend","Weekday"))
act_dum$weekkind <- as.factor(act_dum$weekkind)
str(act_dum)               

two_graph <- act_dum %>%
  group_by(interval, weekkind) %>%
  summarise(steps = mean(steps))
plot_2 <- ggplot(two_graph, aes(x=interval, y=steps, color = weekkind)) +
  geom_line() +
  facet_wrap(~weekkind, ncol = 1, nrow=2)
print(plot_2)
```
